export { default as Login } from './login'
export { default as Register } from './register'
export { default as Home } from './home'
export { default as MyPosts } from './myPosts'
export { default as AllPosts } from './allPosts'